Relax AsyncSequence.collect availability check (#1616)
Motivation:

Tests currently fail with:
> grpc-swift/Tests/GRPCTests/GRPCAsyncClientCallTests.swift:374:61:
error: 'collect()' is only available in macOS 12 or newer

Modifications:

Relax the availability check on the `AsyncSequence` extension. It seems
to arise from the constraint on `AsyncSequence.reduce(into: Result)` which only requires 10.15, not 12.

Result:

Tests should pass.